### ISSUE TITLE
[Node.js Bootcamp] Project 0: Proxy Server - Ready for Review #1

### ISSUE THREAD

**Issue by sriramkrish** [ajayvasagiri/assignment1#1]
My app is complete. /cc @codepathreview @codepath

**Comment by CrabDude** [comment]
You are missing a proper README. This submission is incomplete until you include a proper README.md which includes both the completed "Required"s marked with an "x" and the "time spent". 

Please see the [Submitting Assignments Guide](http://courses.codepath.com/snippets/nodejs_fast_track/submitting_assignments) for how to properly submit an assignment.

**Comment by CrabDude** [comment]
Please update the issue title to the following:

```
[Node.js FastTrack] Project 0: Proxy Server - Ready for Review
```

I'll review once you comment here.

**Comment by CrabDude** [comment]
Please delete this issue since it refers to Project 0.

**Comment by sriramkrish** [comment]
Hi Adam - Can you check now?

Thanks
